dash/urls.py
from django.urls import path, include

from dash.views import team
from dash.views import shared
from dash.views import professionnal
from dash.views import particular
from dash.views import deliverman
from dash.views import staff
from dash.views import realypoint


app_name = "dashboard"

urlpatterns = [
    path("dashboard/", shared.dashboard_view, name="dashboard"),
    path("dashboard/notifications/", shared.get_notifications, name="notifications"),
    path(
        "staff/",
        include(
            [
                path("dashboard/", staff.dashboard, name="staff-dashboard"),
                path("profile/", staff.user_update, name="staff-profile"),
                path("team/", staff.team_member, name="team-member"),
                path("professional/", staff.pro_member, name="pro-member"),
                path("pack/", staff.pack_management, name="pack-management"),
                path("users/", staff.user_management, name="user-management"),
                path(
                    "users/<int:relay_id>/activate/",
                    staff.desactivate_realypoint,
                    name="activate_realypoint_account",
                ),
                path(
                    "users/<int:user_id>/deactivate/",
                    staff.deactivate_user_account,
                    name="deactivate-user-account",
                ),
                path(
                    "users/<int:user_id>/activate/",
                    staff.activate_user_account,
                    name="activate-user-account",
                ),
                path("bills/", staff.bill_management, name="bill-management"),
                path("packages/", staff.package_management, name="package-management"),
                path("contacts/", staff.contact_management, name="contact-management"),
                path(
                    "deliveries/", staff.delivery_management, name="delivery-management"
                ),
                path(
                    "deliverymen/",
                    staff.delivery_man_management,
                    name="delivery_man_management",
                ),
                path("coupons/", staff.coupons, name="coupon-list"),
                path(
                    "realypoint/",
                    staff.realypoint_management,
                    name="realypoint-management",
                ),
                path(
                    "relaypoint/update/<int:pk>",
                    staff.update_realypoint,
                    name="staff-update-relaypoint",
                ),
                path(
                    "team/update/<int:pk>",
                    staff.update_team,
                    name="staff-update-team",
                ),
                path(
                    "users/update/<int:pk>",
                    staff.update_user,
                    name="staff-update-user",
                ),
                path(
                    "team/delete/<int:pk>",
                    staff.delete_team_member,
                    name="staff-delete-team",
                ),
                path(
                    "relaypoint/delete/<int:pk>",
                    staff.delete_relaypoint,
                    name="staff-delete-relaypoint",
                ),
                path(
                    "relay-points/<int:relay_point_id>/rates",
                    staff.relay_point_rate,
                    name="relay-point-rate",
                ),
                path(
                    "relay-points/points/upload",
                    staff.test_upload_departure_arrival,
                    name="test_upload_departure_arrival",
                ),
                path(
                    "deliverymen/update/<int:pk>",
                    staff.update_deliverymen,
                    name="staff-update-deliverymen",
                ),
                path(
                    "users/<int:user_id>/delete/",
                    staff.delete_user_account,
                    name="delete-user-account",
                ),
            ]
        ),
    ),
    path(
        "professionnal/",
        include(
            [
                path(
                    "dashboard/",
                    professionnal.dashboard,
                    name="professionnal-dashboard",
                ),
                path(
                    "profile/", professionnal.user_update, name="professionnal-profile"
                ),
                path(
                    "address-book/",
                    professionnal.address_book_list,
                    name="professionnal-address-book",
                ),
                path(
                    "account/",
                    professionnal.address_book_list,
                    name="professionnal-account",
                ),
                path(
                    "packages/",
                    professionnal.package_list,
                    name="professionnal-package-list",
                ),
                path("relypoint-list/", professionnal.rely_list, name="relypoint_list"),
                path(
                    "revenus/",
                    professionnal.revenus_list,
                    name="professionnal-revenus-list",
                ),
                path(
                    "paiement-compte/",
                    professionnal.paiement_pro,
                    name="paiement_pro",
                ),
                path(
                    "choix-paiement/",
                    professionnal.choice_pro,
                    name="choice_pay_pro",
                ),
                path(
                    "paiement-bancaire/",
                    professionnal.bancaire_pro,
                    name="bank_pay_pro",
                ),
                path(
                    "paiement-wave/",
                    professionnal.wave_pro,
                    name="paiement-wave_pro",
                ),
                path(
                    "paiement-orange-money/",
                    professionnal.orange_pro,
                    name="paiement-orange-money_pro",
                ),
                path(
                    "paiement-free-money/",
                    professionnal.free_pro,
                    name="paiement-free-money_pro",
                ),
                path(
                    "paiement-paydunya/",
                    professionnal.dunya_pro,
                    name="pro_dunya",
                ),
            ]
        ),
    ),
    # url particular
    path(
        "particular/",
        include(
            [
                path(
                    "dashboard/",
                    particular.dashboard,
                    name="particular-dashboard",
                ),
                path("profile/", particular.user_update, name="particular-profile"),
                path(
                    "packages/",
                    particular.package_list,
                    name="particular-package-list",
                ),
                path(
                    "revenus/",
                    particular.revenus_list,
                    name="particular-revenus-list",
                ),
                path(
                    "address-book/",
                    particular.address_book_list,
                    name="particular-address-book",
                ),
                path(
                    "bill_list/",
                    particular.bill_list,
                    name="particular-bill-list",
                ),
                path(
                    "bill/<str:pk>/",
                    particular.bill,
                    name="particular-bill",
                ),
                path(
                    "bill/<int:bill_id>/pdf/",
                    particular.pdf,
                    name="particular-bill-to-pdf",
                ),
                path(
                    "express-service/",
                    particular.express,
                    name="express",
                ),
                path(
                    "paiement-compte/",
                    particular.paiement_part,
                    name="paiement",
                ),
                path(
                    "choice-paiement/",
                    particular.choice,
                    name="choice_pay",
                ),
                path(
                    "paiement-wave/",
                    particular.wave,
                    name="paiement-wave",
                ),
                path(
                    "paiement-bancaire/",
                    particular.bancaire,
                    name="bank_pay",
                ),
                path(
                    "paiement-orange-money/",
                    particular.orange,
                    name="paiement-orange-money",
                ),
                path(
                    "paiement-free-money/",
                    particular.free,
                    name="paiement-free-money",
                ),
                path(
                    "paiement-paydunya/",
                    particular.dunya,
                    name="paiement-dunya",
                ),
            ]
        ),
    ),
    path(
        "team/",
        include(
            [
                path(
                    "dashboard/",
                    team.dashboard,
                    name="team-dashboard",
                ),
                path("profile/", team.user_update, name="team-profile"),
                path(
                    "users/<int:user_id>/deactivate/",
                    team.deactivate_user_account,
                    name="team-deactivate-user-account",
                ),
                path(
                    "address-book/",
                    team.address_book_list,
                    name="team-address-book",
                ),
                path(
                    "packages/",
                    team.package_list,
                    name="team-package-list",

delivery_management/urls.py
# import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "AfricaRelais"
admin.site.index_title = "Admin"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("page.urls", namespace="page")),
    path("", include("delivery.urls", namespace="delivery")),
    path("", include("dash.urls", namespace="dashboard")),
    path("", include("coupons.urls", namespace="coupons")),
    path("auth/", include("user.urls")),
    # path(
    #     "inbox/notifications/",
    #     include("notifications.urls", namespace="notifications"),
    # ),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/models.py
from django.db import models


class BaseTimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ["-created"]

dash/views/deliverman.py
import json
from django.db.models.aggregates import Count, Sum
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from page.models import Contact, RelayPoint
from user.decorators import deliveryman_required
from user.forms import ChangePasswordForm, CustomUserUpdateForm, UpdateProfileForm
from django.contrib import messages
from delivery.models import Package

from user.models import CustomUser


@deliveryman_required
def DelivermanDashboard(request):
    packages = Package.objects.filter(delivered_by=request.user).aggregate(Count("id"))[
        "id__count"
    ]
    income_deliverman = request.user.deliveries.aggregate(Sum("amount"))["amount__sum"]
    all_package = Package.objects.filter(delivered_by=request.user)[:3]
    all_price = Package.objects.all()
    deliverman = Package.objects.all()
    context = {
        "packages": packages,
        "income_deliverman": income_deliverman,
        "all_package": all_package,
        "all_price": all_price,
        "deliverman": deliverman,
    }
    return render(request, "deliverman/dashboard.html", context)


@deliveryman_required
def Profile(request):
    user = request.user
    if request.method == "POST":
        form = CustomUserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Information livreur mise a jour avec succes")
            return redirect("dashboard:deliverman-profile")
        else:
            messages.error(request, f"{form.errors}")
            return redirect("dashboard:deliverman-profile")
    else:
        form = CustomUserUpdateForm(instance=user)
    return render(request, "deliverman/profile.html", {"form": form})


@method_decorator([deliveryman_required], name="dispatch")
class CustomUserUpdateDetailView(UpdateView, DetailView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    avatar_form = UpdateProfileForm
    password_form = ChangePasswordForm
    template_name = "deliverman/profile.html"

    def get(self, request, *args, **kwargs):
        user = request.user
        form = self.form_class(instance=user)
        relay = request.user.point_created.all()
        password_form = self.password_form(user=user)
        return render(
            request,
            self.template_name,
            {
                "form": form,
                "user": user,
                "relay": relay,
                "password_form": password_form,
            },
        )

    def post(self, request, *args, **kwargs):
        user = request.user
        relay = request.user.point_created.all()
        form = self.form_class(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Information modifiée avec succes")
            return redirect("dashboard:deliverman-profile")
        password_form = self.password_form(user, request.POST)
        if password_form.is_valid():
            password_form.save()
            messages.success(request, "Mot de passe modifiée avec succes")
            return redirect("dashboard:deliverman-profile")
        return render(
            request,
            self.template_name,
            {
                "form": form,
                "user": user,
                "relay": relay,
                "password_form": password_form,
            },
        )


@deliveryman_required
def revenue(request):
    return render(request, "deliverman/revenue.html")


@method_decorator([deliveryman_required], name="dispatch")
class AddressBookView(View):
    template_name = "deliverman/address-book.html"
    queryset = Contact.objects.all()

    def get(self, request, *args, **kwargs):
        contacts = self.queryset
        return render(
            request,
            self.template_name,
            {
                "contacts": contacts,
            },
        )


@deliveryman_required
def history(request):
    packages = Package.objects.filter(delivered_by=request.user)
    return render(request, "deliverman/history.html", {"packages": packages})


@deliveryman_required
def income_statistique(request):
    dataset = (
        Package.objects.values("amount")
        .annotate(revenue_count=Count("amount"))
        .order_by("amount")
    )

    categories = list()
    revenue = list()

    for entry in dataset:
        categories.append("%s Class" % entry["price"])
        revenue.append(entry["revenue_count"])

    return render(
        request,
        "deliverman/dashboard.html",
        {
            "categories": json.dumps(categories),
            "revenue": json.dumps(revenue),
        },
    )


@method_decorator([deliveryman_required], name="dispatch")
class Realypoint_ListView(View):
    template_name = "deliverman/list_relypoint.html"

    def get(self, request, *args, **kwargs):
        realypoint = RelayPoint.objects.all()
        return render(request, self.template_name, {"realypoint": realypoint})


user_update = CustomUserUpdateDetailView.as_view()
realypoint_list = Realypoint_ListView.as_view()

dash/views/shared.py
from django.http.response import HttpResponseForbidden
from django.shortcuts import redirect, render
from notifications.signals import notify


from django.contrib.auth.decorators import login_required


@login_required
def dashboard_view(request):
    user = request.user
    if user.is_staff:
        return redirect("dashboard:staff-dashboard")
    elif user.is_deliveryman():
        return redirect("dashboard:dashboard-deliverman")
    elif user.is_professionnal():
        return redirect("dashboard:professionnal-dashboard")
    elif user.is_particular():
        return redirect("dashboard:particular-dashboard")
    elif user.is_team():
        return redirect("dashboard:team-dashboard")
    elif user.is_realypoint():
        return redirect("dashboard:dashboard-realypoint")
    else:
        return HttpResponseForbidden()


@login_required
def get_notifications(request):
    user = request.user
    unread = user.notifications.unread()
    # active = user.notifications.active()
    sen = user.notifications.sent()
    notify.send(user, recipient=user, verb="Chargement de la page")
    return render(
        request,
        "notifications.html",
        {
            "user": user,
            "sen": sen,
            "unread": unread,
        },
    )

dash/templates/professionnal/paiement/choix-compte.html
{% extends "_dash-base.html" %} 
{% load static %}

{% block sidebar %} 
{% include "professionnal/_sidebar.html" %} 
{% endblock sidebar %} 

{% block pagetitle %}
<div class="pagetitle">
    <h1>Compte Prépayer</h1>
    <nav>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item"><a href="/">Accueil</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'dashboard:paiement_pro' %}">Mode de Paiement</a></li>
        </ol>
    </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %}

{% block content %}
<section class="container">
    <div class="row">
        <div class="pagetitle text-center">
            <h1 class="mb-3" >PAYER AVEC : </h1>
            <span class="mb-3"> Je choisit mon mode de paiement </span>
        </div>
        <div class="col-lg-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Wave</h5>
                    <div class="container justify-content-center">
                        <a href="{% url 'dashboard:paiement-wave_pro' %}"><center><img src="{% static 'img/dash/wave.png' %}" alt="Facture" class="img-fluid" width="80"></center></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Orange Monney</h5>
                    <div class="container justify-content-center">
                        <a href="{% url 'dashboard:paiement-orange-money_pro' %}"><center><img src="{% static 'img/dash/Orange_Money-Logo.png' %}" alt="Facture" class="img-fluid" width="140"></center></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Free Monney</h5>
                    <div class="container justify-content-center">
                        <a href="{% url 'dashboard:paiement-free-money_pro' %}"><center><img src="{% static 'img/dash/free.png' %}" alt="Facture" class="img-fluid" width="80"></center></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Paydunya</h5>
                    <div class="container justify-content-center">
                        <a href="{% url 'dashboard:pro_dunya' %}"> <center><img src="{% static 'img/dash/paydunya.png' %}" alt="Facture" class="img-fluid" width="80"></center> </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

dash/templates/professionnal/paiement/compte-paiement.html
{% extends "_dash-base.html" %} 
{% load static %}

{% block sidebar %} 
{% include "professionnal/_sidebar.html" %} 
{% endblock sidebar %} 

{% block pagetitle %}
<div class="pagetitle">
    <h1>Compte Prépayer</h1>
    <nav>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item"><a href="/">Accueil</a></li>
            <li class="breadcrumb-item active">Compte Prépayer</li>
        </ol>
    </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %}

{% block content %}
<section class="container">
    <div class="row">
        <div class="pagetitle text-center">
            <h1 class="mb-3" >RECHARGER MON COMPTE</h1>
            <span class="mb-3"> Je choisit mon mode de paiement </span>
        </div>
        <div class="col-lg-6 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Mobile Money</h5>
                    <div class="mobile-money">
                        <a href="{% url 'dashboard:choice_pay_pro' %}"> <center><img src="{% static 'img/dash/Group_317.png' %}" alt="Facture" class="img-fluid" width="160" height="70"></center> </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6 mt-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Carte Bancaire</h5>
                    <div class="container justify-content-center">
                        <a href="{% url 'dashboard:bank_pay_pro' %}"><center><img src="{% static 'img/dash/debit-card.png' %}" alt="Facture" class="img-fluid" width="140"></center></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container text-center">
        <button type="button" class="btn btn-primary mb-5">Effectuer le payment</button>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sit elementum dui, vitae eget tempor at cursus donec ultricies. Purus diam risus nec porttitor ut libero vulputate vel malesuada. Nunc, quis magna nibh enim a sed fringilla at. Orci duis bibendum a sit tellus elementum id. Etiam mattis rhoncus fermentum at ut turpis eget. Consectetur adipiscing curabitur aliquam, nec, pretium adipiscing consequat. Erat neque, libero quisque in sagittis amet. Sit quis nisl pretium auctor enim, urna nisl elit elit.</p>
    </div>
</section>
{% endblock content %}

dash/templates/professionnal/paiement/paiement-bancaire.html
{% extends "_dash-base.html" %}
{% load static %}

{% block sidebar %}
{% include "professionnal/_sidebar.html" %}
{% endblock sidebar %}

{% block pagetitle %}
<div class="pagetitle">
    <h1>Paiement Carte Bancaire</h1>
    <nav>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item"><a href="/">Accueil</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'dashboard:paiement_pro' %}">Mode de Paiement</a></li>
        </ol>
    </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %}

{% block content %}
  <section class="container">
      <div class="row">
        <div class="pagetitle text-center">
            <h1 class="mb-3" >PAYER AVEC CARTE BANCAIRE: </h1>
            <span class="mb-3"> Je choisit mon mode de paiement </span>
        </div>
        <div class="col-lg-8 mt-3">
            <diV class="card">
                <div class="card-body">
                    <div class="container">
                        <div class="text text-center mt-3">
                            <p style="color:#FFFFFF;">Evitez d'utiliser la carte d'autrui ou de faire
                                plusieurs tentatives ratées sous peine d'être
                                exclu par le système.
                            </p>
                        </div>
                    </div>
                    <form>
                        <div class="form-group mb-3 mt-3">
                          <label for="exampleInputEmail1">NOM COMPLET</label>
                          <input type="text" class="form-control form-control-lg">
                        </div>
                        <div class="form-group mb-3">
                          <label for="exampleInputPassword1">ADRESSE ELECTRONIQUE</label>
                          <input type="email" class="form-control form-control-lg"  aria-describedby="emailHelp">
                        </div>
                        <div class="form-group mb-3">
                            <label>NUMERO DE CARTE BANCAIRE</label>
                            <input type="text" class="form-control form-control-lg">
                        </div>
                        <div class="form-group mb-3">
                            <label>DATE D'EXPIRATION</label>
                            <input type="date" class="form-control form-control-lg">
                        </div>
                        <button type="submit" class="btn btn-primary text-center w-100" style="border-radius: 30px;">PAYER MAINTENANT</button>
                    </form>
                </div>
            </diV>
        </div>
        <div class="prix-compte-bank col-lg-4 mt-3 mb-3">
           <div class="pagetitle mt-3">
               <h5 style="color: #0057FF;">AfricaRelais</h5>
               <p>Montant Total à Payer : <br>  <span style="color: #000D1E; font-weight: bold; text-decoration:underline;">15 000FCFA</span> </p>
           </div>
            <button type="submit" class="btn btn-primary text-center w-100" style="border-radius: 30px; background: #98BBFE;">Voir detail de la profil</button>
        </div>
      </div>
  </section>
{% endblock content %}

dash/templates/professionnal/paiement/paiement-dunya.html
{% extends "_dash-base.html" %}
{% load static %}

{% block sidebar %}
{% include "professionnal/_sidebar.html" %}
{% endblock sidebar %}

{% block pagetitle %}
<div class="pagetitle">
    <h1>Paiement Paydunya</h1>
    <nav>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item"><a href="/">Accueil</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'dashboard:choice_pay_pro' %}">Choisir Mode de Paiement</a></li>
        </ol>
    </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %}

{% block content %}
  <section class="container">
      <div class="row">
        <div class="pagetitle text-center">
            <h1 class="mb-3" >PAYER AVEC PAYDUNYA: </h1>
            <span class="mb-3"> Je choisit mon mode de paiement </span>
        </div>
        <div class="col-lg-8 mt-3">
            <diV class="card">
                <div class="card-body">
                    <div class="container">
                        <div class="text text-center mt-3">
                            <p style="color:#FFFFFF;">Veuillez vous assurer d'avoir assez d'argent
                                sur votre compte paydunya</p>
                        </div>
                    </div>
                    <form>
                        <div class="form-group mb-3 mt-3">
                          <label for="exampleInputEmail1">NOM COMPLET</label>
                          <input type="text" class="form-control form-control-lg">
                        </div>
                        <div class="form-group mb-3">
                          <label for="exampleInputPassword1">ADRESSE ELECTRONIQUE</label>
                          <input type="email" class="form-control form-control-lg"  aria-describedby="emailHelp">
                          <small class="form-text text-muted">Une facture électronique vous sera envoyée à cette adresse email une fois le paiement effectué.</small>
                        </div>
                        <div class="form-group mb-3">
                            <label>TELEPHONE</label>
                            <input type="text" class="form-control form-control-lg">
                        </div>
                        <button type="submit" class="btn btn-primary text-center w-100" style="border-radius: 30px;">PAYER MAINTENANT</button>
                    </form>
                </div>
            </diV>
        </div>
        <div class="prix-compte col-lg-4 mt-3 mb-3">
           <div class="pagetitle mt-3">
               <h5 style="color: #0057FF;">AfricaRelais</h5>
               <p>Montant Total à Payer : <br>  <span style="color: #000D1E; font-weight: bold; text-decoration:underline;">15 000FCFA</span> </p>
           </div>
            <button type="submit" class="btn btn-primary text-center w-100" style="border-radius: 30px; background: #98BBFE;">Voir detail de la profil</button>
        </div>
      </div>
  </section>
{% endblock content %}