dash/urls.py
from django.urls import path, include

from dash.views import team
from dash.views import shared
from dash.views import professionnal
from dash.views import particular
from dash.views import deliverman
from dash.views import staff
from dash.views import realypoint


app_name = "dashboard"

urlpatterns = [
    path("dashboard/", shared.dashboard_view, name="dashboard"),
    path("dashboard/notifications/", shared.get_notifications, name="notifications"),
    path(
        "staff/",
        include(
            [
                path("dashboard/", staff.dashboard, name="staff-dashboard"),
                path("profile/", staff.user_update, name="staff-profile"),
                path("team/", staff.team_member, name="team-member"),
                path("professional/", staff.pro_member, name="pro-member"),
                path("pack/", staff.pack_management, name="pack-management"),
                path("users/", staff.user_management, name="user-management"),
                path(
                    "users/<int:relay_id>/activate/",
                    staff.desactivate_realypoint,
                    name="activate_realypoint_account",
                ),
                path(
                    "users/<int:user_id>/deactivate/",
                    staff.deactivate_user_account,
                    name="deactivate-user-account",
                ),
                path(
                    "users/<int:user_id>/activate/",
                    staff.activate_user_account,
                    name="activate-user-account",
                ),
                path("bills/", staff.bill_management, name="bill-management"),
                path("packages/", staff.package_management, name="package-management"),
                path("contacts/", staff.contact_management, name="contact-management"),
                path(
                    "deliveries/", staff.delivery_management, name="delivery-management"
                ),
                path(
                    "deliverymen/",
                    staff.delivery_man_management,
                    name="delivery_man_management",
                ),
                path("coupons/", staff.coupons, name="coupon-list"),
                path(
                    "realypoint/",
                    staff.realypoint_management,
                    name="realypoint-management",
                ),
                path(
                    "relaypoint/update/<int:pk>",
                    staff.update_realypoint,
                    name="staff-update-relaypoint",
                ),
                path(
                    "team/update/<int:pk>",
                    staff.update_team,
                    name="staff-update-team",
                ),
                path(
                    "users/update/<int:pk>",
                    staff.update_user,
                    name="staff-update-user",
                ),
                path(
                    "team/delete/<int:pk>",
                    staff.delete_team_member,
                    name="staff-delete-team",
                ),
                path(
                    "relaypoint/delete/<int:pk>",
                    staff.delete_relaypoint,
                    name="staff-delete-relaypoint",
                ),
                path(
                    "relay-points/<int:relay_point_id>/rates",
                    staff.relay_point_rate,
                    name="relay-point-rate",
                ),
                path(
                    "relay-points/points/upload",
                    staff.test_upload_departure_arrival,
                    name="test_upload_departure_arrival",
                ),
                path(
                    "deliverymen/update/<int:pk>",
                    staff.update_deliverymen,
                    name="staff-update-deliverymen",
                ),
                path(
                    "users/<int:user_id>/delete/",
                    staff.delete_user_account,
                    name="delete-user-account",
                ),
            ]
        ),
    ),
    path(
        "professionnal/",
        include(
            [
                path(
                    "dashboard/",
                    professionnal.dashboard,
                    name="professionnal-dashboard",
                ),
                path(
                    "profile/", professionnal.user_update, name="professionnal-profile"
                ),
                path(
                    "address-book/",
                    professionnal.address_book_list,
                    name="professionnal-address-book",
                ),
                path(
                    "account/",
                    professionnal.address_book_list,
                    name="professionnal-account",
                ),
                path(
                    "packages/",
                    professionnal.package_list,
                    name="professionnal-package-list",
                ),
                path("relypoint-list/", professionnal.rely_list, name="relypoint_list"),
                path(
                    "revenus/",
                    professionnal.revenus_list,
                    name="professionnal-revenus-list",
                ),
                path(
                    "paiement-compte/",
                    professionnal.paiement_pro,
                    name="paiement_pro",
                ),
                path(
                    "choix-paiement/",
                    professionnal.choice_pro,
                    name="choice_pay_pro",
                ),
                path(
                    "paiement-bancaire/",
                    professionnal.bancaire_pro,
                    name="bank_pay_pro",
                ),
                path(
                    "paiement-wave/",
                    professionnal.wave_pro,
                    name="paiement-wave_pro",
                ),
                path(
                    "paiement-orange-money/",
                    professionnal.orange_pro,
                    name="paiement-orange-money_pro",
                ),
                path(
                    "paiement-free-money/",
                    professionnal.free_pro,
                    name="paiement-free-money_pro",
                ),
                path(
                    "paiement-paydunya/",
                    professionnal.dunya_pro,
                    name="pro_dunya",
                ),
            ]
        ),
    ),
    # url particular
    path(
        "particular/",
        include(
            [
                path(
                    "dashboard/",
                    particular.dashboard,
                    name="particular-dashboard",
                ),
                path("profile/", particular.user_update, name="particular-profile"),
                path(
                    "packages/",
                    particular.package_list,
                    name="particular-package-list",
                ),
                path(
                    "revenus/",
                    particular.revenus_list,
                    name="particular-revenus-list",
                ),
                path(
                    "address-book/",
                    particular.address_book_list,
                    name="particular-address-book",
                ),
                path(
                    "bill_list/",
                    particular.bill_list,
                    name="particular-bill-list",
                ),
                path(
                    "bill/<str:pk>/",
                    particular.bill,
                    name="particular-bill",
                ),
                path(
                    "bill/<int:bill_id>/pdf/",
                    particular.pdf,
                    name="particular-bill-to-pdf",
                ),
                path(
                    "express-service/",
                    particular.express,
                    name="express",
                ),
                path(
                    "paiement-compte/",
                    particular.paiement_part,
                    name="paiement",
                ),
                path(
                    "choice-paiement/",
                    particular.choice,
                    name="choice_pay",
                ),
                path(
                    "paiement-wave/",
                    particular.wave,
                    name="paiement-wave",
                ),
                path(
                    "paiement-bancaire/",
                    particular.bancaire,
                    name="bank_pay",
                ),
                path(
                    "paiement-orange-money/",
                    particular.orange,
                    name="paiement-orange-money",
                ),
                path(
                    "paiement-free-money/",
                    particular.free,
                    name="paiement-free-money",
                ),
                path(
                    "paiement-paydunya/",
                    particular.dunya,
                    name="paiement-dunya",
                ),
            ]
        ),
    ),
    path(
        "team/",
        include(
            [
                path(
                    "dashboard/",
                    team.dashboard,
                    name="team-dashboard",
                ),
                path("profile/", team.user_update, name="team-profile"),
                path(
                    "users/<int:user_id>/deactivate/",
                    team.deactivate_user_account,
                    name="team-deactivate-user-account",
                ),
                path(
                    "address-book/",
                    team.address_book_list,
                    name="team-address-book",
                ),
                path(
                    "packages/",
                    team.package_list,
                    name="team-package-list",

delivery_management/urls.py
# import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "AfricaRelais"
admin.site.index_title = "Admin"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("page.urls", namespace="page")),
    path("", include("delivery.urls", namespace="delivery")),
    path("", include("dash.urls", namespace="dashboard")),
    path("", include("coupons.urls", namespace="coupons")),
    path("auth/", include("user.urls")),
    # path(
    #     "inbox/notifications/",
    #     include("notifications.urls", namespace="notifications"),
    # ),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path

from .views import (
    about,
    condi_vent,
    contact,
    faq,
    favorite_ajax,
    fraud,
    get_relay_points,
    index,
    mention_legal,
    protection,
    relay,
    rembourse,
    result,
    simulation,
    subscription,
    suivi_liv,
)

app_name = "page"

urlpatterns = [
    path("", index, name="home"),
    path("relay/", relay, name="relay"),
    path("get-relay-points/", get_relay_points, name="get_relay_points"),
    path("simulation/", simulation, name="simulation"),
    path("relay/result/", result, name="results"),
    path("favorite_ajax/", favorite_ajax, name="favoriteAjax"),
    path("subscription/", subscription, name="subscription"),
    path("about/", about, name="about"),
    path("faq/", faq, name="faq_page"),
    path("mention-legal", mention_legal, name="mention-legal-page"),
    path("signalement-fraud", fraud, name="fraud-page"),
    path("contactez-nous", contact, name="contact-page"),
    path("suivi-livreur/", suivi_liv, name="suivi-liv-page"),
    path("condition-vente/", condi_vent, name="vente-page"),
    path("reclamation/", rembourse, name="reclamation-page"),
    path("protection-données", protection, name="protection-page"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from user.managers import CustomUserManager
from delivery_management.constants import (
    DELIVERYMAN,
    PARTICULAR,
    PROFESSIONNAL,
    TEAM,
    REALYPOINT,
)


class CustomUser(AbstractUser):

    USER_TYPE = (
        (TEAM, "Responsable"),
        (DELIVERYMAN, "Relayeur"),
        (PROFESSIONNAL, "Professionnel"),
        (PARTICULAR, "Particulier"),
        (REALYPOINT, "Point relais"),
    )
    username = None
    email = models.EmailField(
        unique=True,
        null=True,
    )
    phone = models.CharField(
        max_length=60,
        unique=True,
    )
    city = models.CharField(max_length=60, default="Dakar")
    address = models.CharField(max_length=155, blank=True, null=True)
    avatar = models.ImageField(
        upload_to="avatars/%Y/%m%d",
        null=True,
        blank=True,
    )
    entrprise = models.ForeignKey(
        "user.Entreprise",
        models.SET_NULL,
        null=True,
        blank=True,
    )
    pro_pack = models.ForeignKey(
        "user.ProPack",
        models.SET_NULL,
        null=True,
        blank=True,
    )
    particular_pack = models.ForeignKey(
        "user.ParticularPack",
        models.SET_NULL,
        null=True,
        blank=True,
    )
    user_type = models.CharField(
        max_length=155,
        choices=USER_TYPE,
        default=PARTICULAR,
    )

    objects = CustomUserManager()

    class Meta:
        ordering = ["-date_joined"]

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def is_team(self):
        if self.user_type == TEAM:
            return True
        return False

    def is_professionnal(self):
        if self.user_type == PROFESSIONNAL:
            return True
        return False

    def is_deliveryman(self):
        if self.user_type == DELIVERYMAN:
            return True
        return False

    def is_particular(self):
        if self.user_type == PARTICULAR:
            return True
        return False

    def is_realypoint(self):
        if self.user_type == REALYPOINT:
            return True
        return False

    def save(self, *args, **kwargs):
        if not self.email:
            self.email = None
        super().save(*args, **kwargs)


class Feature(models.Model):
    title = models.CharField(max_length=160)
    # prix
    # nombre de livraison
    # zone

    def __str__(self) -> str:
        return self.title


class Pack(models.Model):
    title = models.CharField(max_length=25, default="Standards")
    price = models.DecimalField(max_digits=12, decimal_places=2)
    features = models.ManyToManyField("user.Feature")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)


class ProPack(Pack):
    pass


class ParticularPack(Pack):
    pass


class Transaction(models.Model):
    EXPENSE = 0
    REVENU = 1
    TRANSACTION_TYPE = (
        (EXPENSE, "Dépense"),
        (REVENU, "Revenue"),
    )
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE)
    account = models.ForeignKey("user.Account", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.amount)


class Account(models.Model):
    user = models.ForeignKey("user.CustomUser", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.email


class Entreprise(models.Model):
    ONE_MAN = "1"
    SMALL = "1-10"
    MEDIUM = "10-50"
    LARGE = "50-100"
    OTHER = "Other"
    COMPANY_SIZE = (
        (ONE_MAN, "Je suis solo entrepreneur"),
        (SMALL, "1 à 10 employés"),
        (MEDIUM, "10 à 50 employés"),
        (LARGE, "50 à 100 employés"),
        (OTHER, "Plus de 100 employés"),
    )
    size = models.CharField(max_length=60, choices=COMPANY_SIZE, default=ONE_MAN)
    name = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

dash/views/shared.py
from django.http.response import HttpResponseForbidden
from django.shortcuts import redirect, render
from notifications.signals import notify


from django.contrib.auth.decorators import login_required


@login_required
def dashboard_view(request):
    user = request.user
    if user.is_staff:
        return redirect("dashboard:staff-dashboard")
    elif user.is_deliveryman():
        return redirect("dashboard:dashboard-deliverman")
    elif user.is_professionnal():
        return redirect("dashboard:professionnal-dashboard")
    elif user.is_particular():
        return redirect("dashboard:particular-dashboard")
    elif user.is_team():
        return redirect("dashboard:team-dashboard")
    elif user.is_realypoint():
        return redirect("dashboard:dashboard-realypoint")
    else:
        return HttpResponseForbidden()


@login_required
def get_notifications(request):
    user = request.user
    unread = user.notifications.unread()
    # active = user.notifications.active()
    sen = user.notifications.sent()
    notify.send(user, recipient=user, verb="Chargement de la page")
    return render(
        request,
        "notifications.html",
        {
            "user": user,
            "sen": sen,
            "unread": unread,
        },
    )

dash/templates/particular/_sidebar.html
{% load static %} {% load static page_tags %}

<li class="nav-item">
  <a class="nav-link {% current_link_active 'particular-package-list' %}"
    href="{% url 'dashboard:particular-package-list' %}">
    <span>
      <img src="{% static 'img/dash/bx_bxs-box (2).png' %}" alt="Colis" class="img-fluid" />
    </span>
    <span>Colis</span>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link {% current_link_active 'particular-bill-list' %}"
    href="{% url 'dashboard:particular-bill-list' %}">
    <span>
      <img src="{% static 'img/dash/icon-park-outline_bill2.png' %}" alt="Facture" class="img-fluid" />
    </span>
    <span>Facture</span>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link {% current_link_active 'paiement' %}" href="{% url 'dashboard:paiement' %}">
    <span>
      <img src="{% static 'img/dash/clarity_dollar-line.png' %}" alt="Facture" class="img-fluid" />
    </span>
    <span>Paiement</span>
  </a>
</li>
<li class="nav-item">
  <a class="nav-link {% current_link_active 'particular-profile' %}" href="{% url 'dashboard:particular-profile' %}">
    <span>
      <img src="{% static 'img/dash/mdi_cog-outline.png' %}" alt="Parametres" class="img-fluid" />
    </span>
    <span>Profile</span>
  </a>
</li>

dash/templates/particular/bill-list.html
{% extends "_dash-base.html" %}
{% load static %}

{% block sidebar %}
{% include "particular/_sidebar.html" %}
{% endblock sidebar %}

{% block pagetitle %}
<div class="pagetitle">
    <h1>Mes Abonnements</h1>
    <nav>
        <ol class="breadcrumb mt-2">
            <li class="breadcrumb-item"><a href="/">Accueil</a></li>
            <li class="breadcrumb-item active">Abonnements</li>
        </ol>
    </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %}

{% block content %}
<div class="row">
    <div class="col-12">

        <div class="card card-body">
            <h2 class="card-title text-center">Mes abonnements</h2>
            <p class="card-text">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus rem consequuntur soluta, error omnis sint
                consectetur culpa animi ratione amet!
            </p>

            {% if not user.particular_pack %}
            <div class="alert alert-warning" role="alert">
                Pas encore souscrit. <a href="{% url 'page:subscription' %}" class="btn btn-primary">Nos packs</a>
            </div>
            {%  else %}

            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Nom du pack</th>
                            <th scope="col">Nombre de livraisons restant</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>{{ user.particular_pack.title }}</td>
                            <td>
                                10
                            </td>
                            <td>
                                <a href="{% url 'page:subscription' %}" class="btn btn-primary">Renouveler</a>
                            </td>
                        </tr>

                    </tbody>
                </table>
            </div>
            {% endif %}


        </div>
    </div>
</div>
</div>
{% endblock content %}

dash/templates/particular/bill.html
{% extends "_dash-base.html" %} {% load static %} {% block sidebar %}
<!-- End Page Title -->{% include "particular/_sidebar.html" %}
<!-- End Page Title -->
{% endblock sidebar %} {% block pagetitle %}
<div class="pagetitle">
  <h1>Mes Abonnements</h1>
  <nav>
    <ol class="breadcrumb mt-2">
      <li class="breadcrumb-item"><a href="/">Accueil</a></li>
      <li class="breadcrumb-item active">Facture</li>
    </ol>
  </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %} {% block content %}
<div class="row">
  <div class="col-12">
    <div class="card card-body">
      <h2 class="card-title text-center">AfricaRelais</h2>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Type de livraison</th>
              <th scope="col">Montant de l'article</th>
              <th scope="col">Prix de livraison</th>
              <th scope="col">Nombre de livraison</th>
              <th scope="col">Prix total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{user.pack}}</td>
              <td><a href="#" class="text-primary">{{package.price}}</a></td>
              <td>{{bill.amount}}</td>
              <td>{{delivery}}</td>
              <td class="fw-bolder">{{price}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <button
        class="btn btn-light text-wh btn-sm col-lg-3 mx-auto mt-2"
        type="submit"
      >
        <a href="{% url 'dashboard:particular-bill-to-pdf' bill.id %}"
          >Importer la facture</a
        >
      </button>
    </div>
  </div>
</div>
{% endblock content %}

dash/templates/particular/profile.html
{% extends "_dash-base.html" %} {% load static %} {% block sidebar %}
<!-- End Page Title -->{% include "particular/_sidebar.html" %}
<!-- End Page Title -->{% endblock sidebar %} {% block pagetitle %}
<div class="pagetitle">
  <h1>Mon profil</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Accueil</a></li>
      <li class="breadcrumb-item active">{{ user.get_full_name }}</li>
    </ol>
  </nav>
</div>
<!-- End Page Title -->
{% endblock pagetitle %} {% block content %}
<section class="section profile">
  <div class="row">
    <div class="col-xl-4">
      <div class="card">
        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
          <img src="
          {% if user.avatar %}
          {{ user.avatar.url }}
          {% else %}
          {% static 'img/noimage.png' %}
          {% endif %}
          " alt="Profile" class="rounded-circle" />
          <h2>{{ user.get_full_name }}</h2>
          <h3 class="mt-2">
            <span class="badge bg-primary">{{user.get_user_type_display}}</span>
          </h3>
        </div>
      </div>

    </div>

    <div class="col-xl-8">
      <div class="card">
        <div class="card-body pt-3">
          <!-- Bordered Tabs -->
          <ul class="nav nav-tabs nav-tabs-bordered">
            <li class="nav-item">
              <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">
                Information personnelle
              </button>
            </li>

            <li class="nav-item">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">
                Mise à jour
              </button>
            </li>
            <li class="nav-item">
              <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">
                Mot de passe
              </button>
            </li>
          </ul>
          <div class="tab-content pt-2">
            <div class="tab-pane fade show active profile-overview" id="profile-overview">
              <div class="row">
                <div class="col-lg-3 col-md-4 label">Nom complet</div>
                <div class="col-lg-9 col-md-8">{{ user.get_full_name }}</div>
              </div>
              <!--
                            <div class="row">
                                <div class="col-lg-3 col-md-4 label">Entreprise</div>
                                <div class="col-lg-9 col-md-8">{{ user.entreprise }}</div>
                            </div> -->

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Adresse</div>
                <div class="col-lg-9 col-md-8">{{ user.address }}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Téléphone</div>
                <div class="col-lg-9 col-md-8">{{ user.phone }}</div>
              </div>

              <div class="row">
                <div class="col-lg-3 col-md-4 label">Email</div>
                <div class="col-lg-9 col-md-8">{{ user.email }}</div>
              </div>
            </div>

            <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
              <!-- Profile Edit Form -->
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row mb-3">
                  <label for="fullName" class="col-md-4 col-lg-3 col-form-label">{{form.first_name.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.first_name}}</div>
                </div>
                <div class="row mb-3">
                  <label for="fullName" class="col-md-4 col-lg-3 col-form-label">{{form.last_name.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.last_name}}</div>
                </div>

                <div class="row mb-3">
                  <label for="Address" class="col-md-4 col-lg-3 col-form-label">{{form.address.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.address}}</div>
                </div>

                <div class="row mb-3">
                  <label for="Phone" class="col-md-4 col-lg-3 col-form-label">{{form.phone.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.phone}}</div>
                </div>

                <div class="row mb-3">
                  <label for="Email" class="col-md-4 col-lg-3 col-form-label">{{form.email.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.email}}</div>
                </div>
                <div class="row mb-3">
                  <label for="Email" class="col-md-4 col-lg-3 col-form-label">{{form.avatar.label}}</label>
                  <div class="col-md-8 col-lg-9">{{form.avatar}}</div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary w-100">
                    Enregistrer
                  </button>
                </div>
              </form>
              <!-- End Profile Edit Form -->
            </div>

            <div class="tab-pane fade pt-3" id="profile-change-password">
              <!-- Change Password Form -->
              <form method="POST">
                {% csrf_token %}
                <div class="row mb-3">
                  <label for="currentPassword"
                    class="col-md-4 col-lg-3 col-form-label">{{password_form.old_password.label}}</label>
                  <div class="col-md-8 col-lg-9">
                    {{password_form.old_password}}
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="newPassword"
                    class="col-md-4 col-lg-3 col-form-label">{{password_form.new_password1.label}}</label>
                  <div class="col-md-8 col-lg-9">
                    {{password_form.new_password1}}
                  </div>
                </div>

                <div class="row mb-3">
                  <label for="renewPassword"
                    class="col-md-4 col-lg-3 col-form-label">{{password_form.new_password2.label}}</label>
                  <div class="col-md-8 col-lg-9">
                    {{password_form.new_password2}}
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary w-100">
                    Changer mot de passe
                  </button>
                </div>
              </form>
              <!-- End Change Password Form -->
            </div>
          </div>
          <!-- End Bordered Tabs -->
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %} {% block extrajs %}
<script>
  $(document).ready(function () {
    var readURL = function (input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader()
        reader.onload = function (e) {
          $('.profile-pic').attr('src', e.target.result)
        }
        reader.readAsDataURL(input.files[0])
      }
    }
    $('.file-upload').on('change', function () {
      readURL(this)
    })
    $('.upload-button').on('click', function () {
      $('.file-upload').click()
    })

    // update profile picture
    var $avatarForm = $('.avatar-form')
    $avatarForm.submit(function (event) {
      event.preventDefault()
      var files = $('#id_avatar')[0].files[0]
      var formData = new FormData()
      formData.append('csrfmiddlewaretoken', '{{ csrf_token }}')
      formData.append('avatar', files)
      console.log('this is my profile', files)
      var $thisURL = $avatarForm.attr('data-url') || window.loaction.href
      $.ajax({
        method: 'POST',
        url: $thisURL,
        data: formData,
        contentType: false,
        processData: false,
        success: handleSuccess,
        error: handleError,
      })

      function handleSuccess(data) {
        console.log('succes', data)
        // $avatarForm[0].reset()
      }

      function handleError(ThrowError) {
        console.log('error', ThrowError)
      }
    })

    // update-password
    var $updatePasswordForm = $('.update-password')
    $updatePasswordForm.submit(function (event) {
      event.preventDefault()
      var $formData = $updatePasswordForm.serialize()
      var $thisURL =
        $updatePasswordForm.attr('data-url') || window.loaction.href
      $.ajax({
        method: 'POST',
        url: $thisURL,
        data: $formData,
        success: handleSuccess,
        error: handleError,
      })

      function handleSuccess(data) {
        if (data.is_error) {
          alert(data.errors)
        }
        // $updatePasswordForm[0].reset()
      }

      function handleError(ThrowError) {}
    })
  })
</script>
{% endblock extrajs %}