dash/urls.py
from django.urls import path, include

from dash.views import team
from dash.views import shared
from dash.views import professionnal
from dash.views import particular
from dash.views import deliverman
from dash.views import staff
from dash.views import realypoint


app_name = "dashboard"

urlpatterns = [
    path("dashboard/", shared.dashboard_view, name="dashboard"),
    path("dashboard/notifications/", shared.get_notifications, name="notifications"),
    path(
        "staff/",
        include(
            [
                path("dashboard/", staff.dashboard, name="staff-dashboard"),
                path("profile/", staff.user_update, name="staff-profile"),
                path("team/", staff.team_member, name="team-member"),
                path("professional/", staff.pro_member, name="pro-member"),
                path("pack/", staff.pack_management, name="pack-management"),
                path("users/", staff.user_management, name="user-management"),
                path(
                    "users/<int:relay_id>/activate/",
                    staff.desactivate_realypoint,
                    name="activate_realypoint_account",
                ),
                path(
                    "users/<int:user_id>/deactivate/",
                    staff.deactivate_user_account,
                    name="deactivate-user-account",
                ),
                path(
                    "users/<int:user_id>/activate/",
                    staff.activate_user_account,
                    name="activate-user-account",
                ),
                path("bills/", staff.bill_management, name="bill-management"),
                path("packages/", staff.package_management, name="package-management"),
                path("contacts/", staff.contact_management, name="contact-management"),
                path(
                    "deliveries/", staff.delivery_management, name="delivery-management"
                ),
                path(
                    "deliverymen/",
                    staff.delivery_man_management,
                    name="delivery_man_management",
                ),
                path("coupons/", staff.coupons, name="coupon-list"),
                path(
                    "realypoint/",
                    staff.realypoint_management,
                    name="realypoint-management",
                ),
                path(
                    "relaypoint/update/<int:pk>",
                    staff.update_realypoint,
                    name="staff-update-relaypoint",
                ),
                path(
                    "team/update/<int:pk>",
                    staff.update_team,
                    name="staff-update-team",
                ),
                path(
                    "users/update/<int:pk>",
                    staff.update_user,
                    name="staff-update-user",
                ),
                path(
                    "team/delete/<int:pk>",
                    staff.delete_team_member,
                    name="staff-delete-team",
                ),
                path(
                    "relaypoint/delete/<int:pk>",
                    staff.delete_relaypoint,
                    name="staff-delete-relaypoint",
                ),
                path(
                    "relay-points/<int:relay_point_id>/rates",
                    staff.relay_point_rate,
                    name="relay-point-rate",
                ),
                path(
                    "relay-points/points/upload",
                    staff.test_upload_departure_arrival,
                    name="test_upload_departure_arrival",
                ),
                path(
                    "deliverymen/update/<int:pk>",
                    staff.update_deliverymen,
                    name="staff-update-deliverymen",
                ),
                path(
                    "users/<int:user_id>/delete/",
                    staff.delete_user_account,
                    name="delete-user-account",
                ),
            ]
        ),
    ),
    path(
        "professionnal/",
        include(
            [
                path(
                    "dashboard/",
                    professionnal.dashboard,
                    name="professionnal-dashboard",
                ),
                path(
                    "profile/", professionnal.user_update, name="professionnal-profile"
                ),
                path(
                    "address-book/",
                    professionnal.address_book_list,
                    name="professionnal-address-book",
                ),
                path(
                    "account/",
                    professionnal.address_book_list,
                    name="professionnal-account",
                ),
                path(
                    "packages/",
                    professionnal.package_list,
                    name="professionnal-package-list",
                ),
                path("relypoint-list/", professionnal.rely_list, name="relypoint_list"),
                path(
                    "revenus/",
                    professionnal.revenus_list,
                    name="professionnal-revenus-list",
                ),
                path(
                    "paiement-compte/",
                    professionnal.paiement_pro,
                    name="paiement_pro",
                ),
                path(
                    "choix-paiement/",
                    professionnal.choice_pro,
                    name="choice_pay_pro",
                ),
                path(
                    "paiement-bancaire/",
                    professionnal.bancaire_pro,
                    name="bank_pay_pro",
                ),
                path(
                    "paiement-wave/",
                    professionnal.wave_pro,
                    name="paiement-wave_pro",
                ),
                path(
                    "paiement-orange-money/",
                    professionnal.orange_pro,
                    name="paiement-orange-money_pro",
                ),
                path(
                    "paiement-free-money/",
                    professionnal.free_pro,
                    name="paiement-free-money_pro",
                ),
                path(
                    "paiement-paydunya/",
                    professionnal.dunya_pro,
                    name="pro_dunya",
                ),
            ]
        ),
    ),
    # url particular
    path(
        "particular/",
        include(
            [
                path(
                    "dashboard/",
                    particular.dashboard,
                    name="particular-dashboard",
                ),
                path("profile/", particular.user_update, name="particular-profile"),
                path(
                    "packages/",
                    particular.package_list,
                    name="particular-package-list",
                ),
                path(
                    "revenus/",
                    particular.revenus_list,
                    name="particular-revenus-list",
                ),
                path(
                    "address-book/",
                    particular.address_book_list,
                    name="particular-address-book",
                ),
                path(
                    "bill_list/",
                    particular.bill_list,
                    name="particular-bill-list",
                ),
                path(
                    "bill/<str:pk>/",
                    particular.bill,
                    name="particular-bill",
                ),
                path(
                    "bill/<int:bill_id>/pdf/",
                    particular.pdf,
                    name="particular-bill-to-pdf",
                ),
                path(
                    "express-service/",
                    particular.express,
                    name="express",
                ),
                path(
                    "paiement-compte/",
                    particular.paiement_part,
                    name="paiement",
                ),
                path(
                    "choice-paiement/",
                    particular.choice,
                    name="choice_pay",
                ),
                path(
                    "paiement-wave/",
                    particular.wave,
                    name="paiement-wave",
                ),
                path(
                    "paiement-bancaire/",
                    particular.bancaire,
                    name="bank_pay",
                ),
                path(
                    "paiement-orange-money/",
                    particular.orange,
                    name="paiement-orange-money",
                ),
                path(
                    "paiement-free-money/",
                    particular.free,
                    name="paiement-free-money",
                ),
                path(
                    "paiement-paydunya/",
                    particular.dunya,
                    name="paiement-dunya",
                ),
            ]
        ),
    ),
    path(
        "team/",
        include(
            [
                path(
                    "dashboard/",
                    team.dashboard,
                    name="team-dashboard",
                ),
                path("profile/", team.user_update, name="team-profile"),
                path(
                    "users/<int:user_id>/deactivate/",
                    team.deactivate_user_account,
                    name="team-deactivate-user-account",
                ),
                path(
                    "address-book/",
                    team.address_book_list,
                    name="team-address-book",
                ),
                path(
                    "packages/",
                    team.package_list,
                    name="team-package-list",

delivery/urls.py
from django.urls import path

from .views import (
    relayer,
    SendPackageView,
    get_delivery_price,
    package_tracking,
    tracking_results,
)

app_name = "delivery"

urlpatterns = [
    path(
        "send-package/",
        SendPackageView.as_view(),
        name="send-package",
    ),
    path("tracking/", package_tracking, name="package-tracking"),
    path(
        "tracking/results/",
        tracking_results,
        name="tracking-results",
    ),
    path(
        "get-delivery-price/",
        get_delivery_price,
        name="get_delivery_price",
    ),
    path(
        "relayer/",
        relayer,
        name="relayer_page",
    ),
]

delivery_management/urls.py
# import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "AfricaRelais"
admin.site.index_title = "Admin"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("page.urls", namespace="page")),
    path("", include("delivery.urls", namespace="delivery")),
    path("", include("dash.urls", namespace="dashboard")),
    path("", include("coupons.urls", namespace="coupons")),
    path("auth/", include("user.urls")),
    # path(
    #     "inbox/notifications/",
    #     include("notifications.urls", namespace="notifications"),
    # ),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/urls.py
from django.urls import path

from .views import (
    about,
    condi_vent,
    contact,
    faq,
    favorite_ajax,
    fraud,
    get_relay_points,
    index,
    mention_legal,
    protection,
    relay,
    rembourse,
    result,
    simulation,
    subscription,
    suivi_liv,
)

app_name = "page"

urlpatterns = [
    path("", index, name="home"),
    path("relay/", relay, name="relay"),
    path("get-relay-points/", get_relay_points, name="get_relay_points"),
    path("simulation/", simulation, name="simulation"),
    path("relay/result/", result, name="results"),
    path("favorite_ajax/", favorite_ajax, name="favoriteAjax"),
    path("subscription/", subscription, name="subscription"),
    path("about/", about, name="about"),
    path("faq/", faq, name="faq_page"),
    path("mention-legal", mention_legal, name="mention-legal-page"),
    path("signalement-fraud", fraud, name="fraud-page"),
    path("contactez-nous", contact, name="contact-page"),
    path("suivi-livreur/", suivi_liv, name="suivi-liv-page"),
    path("condition-vente/", condi_vent, name="vente-page"),
    path("reclamation/", rembourse, name="reclamation-page"),
    path("protection-données", protection, name="protection-page"),
]

delivery_management/templates/partials/_alerts.html
{% if messages %}

{% for message in messages %}

<div
  class="alert {% if message.tags == 'success' %} alert-{{ message.tags }} {% else %} alert-warning {% endif %}  alert-dismissible fade show mx-auto col-6"
  role="alert" style="margin-top: 100px;">
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endfor %}
{% endif %}

delivery_management/templates/partials/_breadcrumbs.html
<section class="breadcrumbs">
  <div class="container">

    <ol>
      <li><a href="/">Accueil</a></li>
      <li>Suivi de colis</li>
    </ol>
    <h2>Suivre votre colis en temps réel</h2>

  </div>
</section>

delivery_management/templates/partials/_carousels.html
{% load static %}

<section id="hero" class="hero d-flex align-items-center">
  <div class="container-fluid">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for carousel in carousels %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <img src="
            {% if carousel.image %}
            {{ carousel.image.url }}
            {% else %}
            {% static 'img/slide-1.png' %}
            {% endif %}
      " class="d-block w-100" alt="{{ carousel.title }}">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</section>

delivery_management/templates/partials/_footer.html
{% load static %}

<footer id="footer" class="footer">

    <div class="footer-top">
        <div class="container">
            <div class="row gy-4">


                <div class="col-lg-2 col-6 footer-links">
                    <h4>AfricaRelais</h4>
                    <ul>
                        <li><a href="{% url 'page:about' %}">A propos de nous</a>
                        </li>
                        <li><a href="{% url 'delivery:send-package' %}">Envoi de colis</a></li>
                        <li><a href="{% url 'delivery:package-tracking' %}">Suivi du colis</a></li>
                        </li>
                        <li><a href="{% url 'page:subscription' %}">Abonnement</a></li>
                        <li><a href="{% url 'page:simulation' %}">Simulation de prix</a></li>
                    </ul>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>REJOIGNEZ-NOUS</h4>
                    <ul>
                        <li><a href="https://forms.gle/TT18da75n9ctBsbZA" target="_blank">Devenir Relayeur</a></li>
                        <li><a href="https://forms.gle/3otKEZ1Rf7ZkpufZ9" target="_blank">Devenir point relais</a></li>
                        <li><a href="{% url 'page:vente-page' %}">CGV</a></li>
                        <li><a href="https://wa.me/+221784283907?text=Bonjour AfricaRelais, Reclamation"
                                target="_blank">Contactez nous</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-12 footer-links">
                    <h4>AIDE</h4>
                    <ul>
                        <li><a href="{% url 'page:faq_page' %}">FAQ</a></li>
                        <li><a href="{% url 'page:mention-legal-page' %}">Mentions légales</a></li>
                        <li><a href="{% url 'page:fraud-page' %}">Information fraude</a></li>
                        <li><a href="{% url 'page:protection-page' %}">Protection des données</a></li>
                        <li><a href="https://wa.me/+221784283907?text=Bonjour AfricaRelais, Reclamation"
                                target="_blank">Service de réclamations</a></li>

                    </ul>

                </div>
                <div class="col-lg-5 col-md-12 footer-info">
                    <a href="/" class="logo d-flex align-items-center">
                        <img src="{% static 'img/logo.png' %}" alt="">
                        <span>AfricaRelais</span>
                    </a>
                    <p>Suivez nous</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                    <div class="footer-payement mt-4">
                        <img src="{% static 'img/Group_316.png' %}" alt="">
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>AfricaRelais</span></strong>. Tous les droits réservés 2022
        </div>
        <div class="credits">
            Propulsé par <a href="https://www.defarkat.com/" target="_blanc">Defarkat</a>
        </div>
    </div>
</footer>

delivery_management/templates/partials/_header.html
{% load static page_tags %} {% block extrastyle %}
<style>
  .getstarted.scrollto.espace {
    background: linear-gradient(180deg, #0057ff 0%, #012f88 100%);
    border-radius: 20px;
  }

  .getstarted.scrollto.connect {
    border-radius: 20px;
    width: 140px;
    height: 40px;
    justify-content: center;
    margin-right: 2px;
  }

  .getstarted.scrollto.login {
    border-radius: 20px;
    background: linear-gradient(180deg, #0057ff 0%, #012f88 100%);
    width: 140px;
    height: 40px;
    justify-content: center;
    margin-left: 15px;
  }

  #logo-title {
    color: #0057ff;
    font-size: 1rem;
  }

  .btn-button {
    border: 2px solid #0057ff;
    border-radius: 20px;
  }

  .tab-nav {
    display: flex;
    justify-content: center;
  }
</style>
{% endblock extrastyle %}

<header id="header" class="header fixed-top">
  <div class="container d-flex align-items-center justify-content-between">
    <a href="/" class="logo d-flex align-items-center">
      <img src="{% static 'img/logo.png' %}" alt="" />
      <span id="logo-title">AfricaRelais</span>
    </a>
    <nav id="navbar" class="navbar">
      <ul>
        <li>
          <a class="nav-link scrollto {% current_link_active 'send-package' %}"
            href="{% url 'delivery:send-package' %}">Envoi de colis</a>
        </li>
        <li>
          <a class="nav-link scrollto {% current_link_active 'package-tracking' %}"
            href="{% url 'delivery:package-tracking' %}">Suivi de colis</a>
        </li>
        <li>
          <a class="nav-link scrollto {% current_link_active 'relay' %}" href="{% url 'page:relay' %}">Point relais</a>
        </li>
        <li>
          <a class="nav-link scrollto {% current_link_active 'relayer_page' %}"
            href="{% url 'delivery:relayer_page' %}">relayeur</a>
        </li>
        <li>
          <a class="nav-link scrollto {% current_link_active 'subscription' %}"
            href="{% url 'page:subscription' %}">Abonnement</a>
        </li>

        {% if user.is_authenticated %}
        <li>
          <a class="getstarted scrollto espace {% current_link_active 'dashboard' %}"
            href="{% url 'dashboard:dashboard' %}">Mon espace</a>
        </li>
        {% else %}
        <li>
          <a class="getstarted scrollto connect btn-button {% current_link_active 'login' %} btn-bg-inverse"
            href="{% url 'login' %}">Se connecter</a>
        </li>
        <li>
          <a class="getstarted scrollto login {% current_link_active 'register' %}"
            href="{% url 'register' %}">S'inscrire</a>
        </li>
        {% endif %}
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>
    <!-- .navbar -->
  </div>
</header>